"""Add discovered status

Revision ID: 1149fb28cad6
Revises: 6f660a2cfa9d
Create Date: 2026-01-21 17:41:25.949232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1149fb28cad6'
down_revision: Union[str, Sequence[str], None] = '6f660a2cfa9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_addresses', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('ALLOCATED', 'RESERVED', 'AVAILABLE', 'DHCP_POOL', 'DISCOVERED', name='ipstatus'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_addresses', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ALLOCATED', 'RESERVED', 'AVAILABLE', 'DHCP_POOL', 'DISCOVERED', name='ipstatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)

    # ### end Alembic commands ###
