"""Initial migration

Revision ID: 6f660a2cfa9d
Revises: 
Create Date: 2026-01-21 17:21:50.088049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f660a2cfa9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_hostname'), 'devices', ['hostname'], unique=False)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_table('subnets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('network_address', sa.String(), nullable=True),
    sa.Column('prefix_length', sa.Integer(), nullable=True),
    sa.Column('gateway', sa.String(), nullable=True),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subnets_id'), 'subnets', ['id'], unique=False)
    op.create_index(op.f('ix_subnets_name'), 'subnets', ['name'], unique=False)
    op.create_index(op.f('ix_subnets_network_address'), 'subnets', ['network_address'], unique=False)
    op.create_table('ip_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ALLOCATED', 'RESERVED', 'AVAILABLE', 'DHCP_POOL', name='ipstatus'), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('interface_name', sa.String(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('healthcheck_status', sa.String(), nullable=True),
    sa.Column('subnet_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['subnet_id'], ['subnets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_addresses_address'), 'ip_addresses', ['address'], unique=True)
    op.create_index(op.f('ix_ip_addresses_id'), 'ip_addresses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ip_addresses_id'), table_name='ip_addresses')
    op.drop_index(op.f('ix_ip_addresses_address'), table_name='ip_addresses')
    op.drop_table('ip_addresses')
    op.drop_index(op.f('ix_subnets_network_address'), table_name='subnets')
    op.drop_index(op.f('ix_subnets_name'), table_name='subnets')
    op.drop_index(op.f('ix_subnets_id'), table_name='subnets')
    op.drop_table('subnets')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_hostname'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
