"""add_hostname_to_ipaddress

Revision ID: 7219b758cb71
Revises: 8328e3bfc356
Create Date: 2026-01-21 20:22:54.962649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7219b758cb71'
down_revision: Union[str, Sequence[str], None] = '8328e3bfc356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hostname', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_addresses', schema=None) as batch_op:
        batch_op.drop_column('hostname')

    # ### end Alembic commands ###
