"""add scan metadata to subnets

Revision ID: 8fa34a591b89
Revises: 1149fb28cad6
Create Date: 2026-01-21 18:08:24.304996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa34a591b89'
down_revision: Union[str, Sequence[str], None] = '1149fb28cad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subnets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_scan', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('scan_status', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subnets', schema=None) as batch_op:
        batch_op.drop_column('scan_status')
        batch_op.drop_column('last_scan')

    # ### end Alembic commands ###
